@startuml
hide circle

database DB {
    entity users {
        id int (PK)
        --
        email varchar not null
    }

    entity tasks {
        id int (PK)
        --
        user_id int (FK)
        name varchar
    }

    entity tags {
        id int (PK)
        --
        name varchar
    }

    entity task_tags {
        id int (PK)
        --
        task_id int (FK)
        tag_id int (FK)
    }
}

users |o-|{ tasks
tasks |o-|{ task_tags
tags |o--|{ task_tags
@enduml

